services:
  maria-db:
    container_name: maria-db-vermity
    hostname: maria-db
    image: 'mariadb:latest'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    networks:
        - shared

  vermity-backend:
    container_name: vermity-backend
    build:
        context: .
    restart: unless-stopped
    ports:
        - '9913:8081'
    networks:
      - shared
    depends_on:
      maria-db:
        condition: service_healthy
    environment:
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_USER=myuser'
      - 'MARIADB_HOST=maria-db-vermity'
      - 'MARIADB_PORT=3306'
      - 'MARIADB_DATABASE=mydatabase'

networks:
  shared:
volumes:
    mariadb-data: